server:
  port: 8080
spring:
  application:
    name: converter-audio
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKAHOSTNAME:localhost}:8761/eureka/
  instance:
    metadataMap:
      convertFrom:
        - audio/x-ms-wma
        - audio/aiff
        - audio/x-aiff
        - audio/aac
        - audio/x-aac
        - audio/flac
        - audio/x-flac
      convertTo: audio/mpeg
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

converterUrl: http://ffmpeg:3000
